services:
  api:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - minio
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: eng_agents
  redis:
    image: redis:7
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: pass
    ports:
      - "9000:9000"
  frontend:
    build:
      context: ..
      dockerfile: apps/frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://api:8000
    ports:
      - "3000:3000"


